### ISSUE TITLE
Update kss dependency - Post install fails on ubuntu 14 / node version 12

### ISSUE THREAD

**Issue by michaelBenin** [indieisaconcept/grunt-styleguide#63]
Post install fails installing node sass from kss dependency. 

```
eastny@east-ny-hp:~/Projects/node-startup$ npm i
npm WARN package.json node-startup@0.0.2 bugs.url field must be a string url. Deleted.
npm WARN package.json node-startup@0.0.2 Normalized value of bugs field is an empty object. Deleted.
/
> node-sass@0.9.6 install /home/eastny/Projects/node-startup/node_modules/grunt-styleguide/node_modules/kss/node_modules/node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/eastny/Projects/node-startup/node_modules/grunt-styleguide/node_modules/kss/node_modules/node-sass/build'
  CXX(target) Release/obj.target/binding/binding.o
make: g++: Command not found
make: *** [Release/obj.target/binding/binding.o] Error 127
make: Leaving directory `/home/eastny/Projects/node-startup/node_modules/grunt-styleguide/node_modules/kss/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/eastny/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.16.0-31-generic
gyp ERR! command "node" "/home/eastny/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/eastny/Projects/node-startup/node_modules/grunt-styleguide/node_modules/kss/node_modules/node-sass
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
Build failed
npm ERR! Linux 3.16.0-31-generic
npm ERR! argv "node" "/home/eastny/.nvm/versions/node/v0.12.0/bin/npm" "i"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eastny/Projects/node-startup/npm-debug.log
eastny@east-ny-hp:~/Projects/node-startup$ 
```

https://www.npmjs.com/package/kss - to latest version

**Comment by indieisaconcept** [comment]
@michaelBenin if you are using kss exclusively I recommend you use:

https://www.npmjs.com/package/grunt-kss
